---
kind: "operation"
client: "atomist-bot"
generator:
  name: "NewRugProject"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.29.0"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "0f425945c62957ccc2ccb63e9980e6f78b97a4a1"
    sha: "0f42594"
  parameters:
    - "owner": "akstewart"
    - "description": "PMD and CheckStyle code analysis"
    - "version": "0.1.0"

---
kind: "operation"
client: "atomist-bot"
editor:
  name: "AddTypeScriptEventHandler"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.29.0"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "0f425945c62957ccc2ccb63e9980e6f78b97a4a1"
    sha: "0f42594"
  parameters:
    - "handlerName": "CodeReviewOnPush"
    - "description": "Run code analysis"
    - "pathExpression": "/Tag()"

